### ISSUE TITLE
Bar chart tool error

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/gvl_image_playbook#16]
Bar chart tool does not work: File "/mnt/galaxy/galaxy-app/tools/plotting/bar_chart.py", line 26, in <module>
import Gnuplot, Gnuplot.funcutils
ImportError: No module named Gnuplot

This tool uses a virtual environment(?) and Numpy package has to be added to the virtual environment. Ask Derek for details.

**Comment by madisonkeene** [comment]
Derek's fix: udo apt-get install gnuplot
sudo su - galaxy
cd /mnt/galaxy/galaxy-app/
source .venv/bin/activate
cd ../tmp
mkdir gnuplot
cd gnuplot/
wget http://sourceforge.net/projects/gnuplot-py/files/latest/download?source=files
mv download\?source=files gnuplot-py-1.8.tar.gz
tar -xzf gnuplot-py-1.8.tar.gz
cd gnuplot-py-1.8/
pip install NumPy
python setup.py install

**Comment by jessicachung** [comment]
This still doesn't work. I can import Gnuplot with /usr/bin/python, but not with the galaxy virtualenv.

**Comment by nuwang** [comment]
The gnuplot and numpy packages have been installed in Galaxy's virtualenv in addition to a systemwide installation.
