### ISSUE TITLE
Galaxy reports bugs

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/gvl_image_playbook#17]
Bigs in Galaxy Reports
1. Job per user displays only top 50 jobs, other pages are blank. This is an old bug, it exists in GVL-3.04
2. User disk usage: it shows only the default 60 users. Putting any other number of users produces "Server Error" message. This is a new bug, it was ok in previous GVL versions.
All bugs were detected on Galaxy-qld.

**Comment by madisonkeene** [comment]
Need to file bug with Galaxy if not working in 4.1

**Comment by nuwang** [comment]
@igormakunin Is this still an issue with the latest Galaxy in 4.1?

**Comment by igormakunin** [comment]
@nuwang I cannot check it because Galaxy Reports does not start on GVL-4.1.0, see Simon's comment
