### ISSUE TITLE
No link to UCSC Genome Browser for BAM files

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/gvl_image_playbook#20]
no link to UCSC Genome Browser for hg19 BAM files

**Comment by madisonkeene** [comment]
Fix for the problem.
/mnt/galaxy/galaxy-app/config//galaxy.ini

# change :

ucsc_display_sites = gvlmain,test,archaea,ucla

# to :

ucsc_display_sites = main,test,archaea,ucla

/mnt/galaxy/galaxy-app/tool-data/shared/ucsc/ucsc_build_sites.txt

# change: gvlmain http://ucsc.genome.edu.au/cgi-bin/hgTracks?

# to

main http://genome.ucsc.edu/cgi-bin/hgTracks?
(must be tub separated)

(optional) /mnt/galaxy/galaxy-app/config//galaxy.ini

# change: ucsc_build_sites = /mnt/galaxy/galaxy-app/tool-data/shared/ucsc/ucsc_build_sites.txt.sample

# to

ucsc_build_sites = /mnt/galaxy/galaxy-app/tool-data/shared/ucsc/ucsc_build_sites.txt

**Comment by madisonkeene** [comment]
Note for myself: dm3 works just fine after the fix, hg38 - no link, because hg38 is not in ucsc_build_sites.txt file.
mm9, mm10, hg19 - ok (all three have links to UCSC main)

**Comment by madisonkeene** [comment]
Fixed galaxy.ini to use corerct ucsc_display_sites list and changed ucsc_build_sites.txt to use default ucsc server as given below.

**Comment by nuwang** [comment]
@igormakunin Can you please check this as well while on this issue? Will let you know when the new build is ready

**Comment by igormakunin** [comment]
@nuwang The hg19 visualisation issue has gone. The ticket can be closed.
