### ISSUE TITLE
Add latest version of SAMtools to build script

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/gvl_image_playbook#35]
To fix the samtools issue where users can crash galaxy.

QLD report that sorting bam files crashes galaxy and leaves tmp files that then accumulate -- kills python process, repeatable! (gvl-lab email 20 April)  recreate here, or in 4.1.?  - QLD to create bug report - repeatable at melb-test - other people submitted to galaxy list, galaxy using local environment to run samtools - fix update samtools to 1.2 in local environment.

**Comment by nuwang** [comment]
@jessicachung Is this no longer necessary then? Or should we update samtools anyway to the latest version just in case?

**Comment by jessicachung** [comment]
I haven't been able to crash galaxy in 4.1 by indexing an unsorted bam file (the job still fails, but galaxy doesn't crash).

It might still be a good idea to update samtools, but it's no longer a critical issue.

**Comment by igormakunin** [comment]
@nuwang I can confirm: no crash during sorting of a BAM file with 'the crash text string'. SAMtools>sort has produced a functional output (green file). However, the contig oder in coordinate-sorted BAMs might differ from the assembly, eg chr3, chr2. Both single and paired-end BAMs were tested. The ticket can be closed.
