### ISSUE TITLE
Remove venburritto startup from .profile and .bashrc.

### ISSUE THREAD

**Issue by Slugger70** [gvlproject/gvl_image_playbook#37]
Loading venvburritto startup in the .profile and .bashrc sets the $PYTHONPATH undesirably. It really screws up brew installations.

Leave it present and load it manually if it's actually required for anything.

**Comment by afgane** [comment]
`venvburitto` is used by CloudMan - it's virtualenv is created there. At this point, it's an artifact of the past and we could remove it but it does actually link into several in at least Ansible role and `cm_boot.py` (https://github.com/galaxyproject/cloudman/blob/master/cm_boot.py#L440) so the image and CloudMan would need to be updated simultaneously. The annoying thing is that such change would then prevent different versions of the image and CloudMan to work with each other and potentially cause errors when users try to launch it.

Overall, I'm in favor of removing `venvburitto` but just need to test it well.

**Comment by nuwang** [comment]
Fixed in commits: https://github.com/nuwang/cloudman/commit/35aa1d2ae74fdd623e6634aa1c85c8d028197274
and https://github.com/nuwang/ansible-cloudman-image/commit/716298c4ed1d74f164972d1db91dbba86afaa714
A build is underway, and this issue can be moved to in-test when the build is complete.

**Comment by afgane** [comment]
Nice going.

**Comment by nuwang** [comment]
@Slugger70 Can you check it's all good now?
