### ISSUE TITLE
Some Galaxy tools are using the wrong version of R

### ISSUE THREAD

**Issue by jessicachung** [gvlproject/gvl_image_playbook#39]
Tools such as "Correlation for numeric columns" and "Scatterplot" are using the wrong version of R. This can be fixed by adding the line

```
source /mnt/galaxy/tools/R/2.11.0/devteam/package_r_2_11_0/5824d2b3bc8b/env.sh
```

into 

```
/mnt/galaxy/tools/rpy/1.0.3/devteam/package_rpy_1_0_3/82170c94ca7c/env.sh
```

once the filesystem has been built.

**Comment by nuwang** [comment]
@jessicachung @Slugger70 Can you explain this problem to me a bit more? So is the issue that rpy is using the wrong version of R for some reason? Why are there two versions of R?

In any case, we can fix this after the tool installation bit with lineinfile.

**Comment by nuwang** [comment]
Fixed in: https://github.com/gvlproject/gvl.ansible.filesystem/commit/db6a3a77e91c0987b5d9d975b41c4610bb06ec12
