### ISSUE TITLE
Synchronise users between Master and workers

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/gvl_image_playbook#40]
The problem is that users are not replicated between master and workers - as a result, jobs can fail when an attempt is made to execute as that user (e.g. the researcher user). Torsten suggested that we make the master run some kind of auth server, say ldap, which the workers are synchronised too. That way, standard unix commands can be used to manage users across the cluster.

**Comment by nuwang** [comment]
Based on Derek's proposal, the following has been implemented as an immediate solution: https://github.com/gvlproject/gvl.ansible.image/commit/e320f75ac3db0160ac24ba9c418574f102d23c13

Later on, perhaps for GVL 5.0.0, we can try out something more comprehensive, like Globus or LDAP.
