### ISSUE TITLE
GVL-4.1 Get Data is hooked to defunct GVL UCSC genome browser mirror

### ISSUE THREAD

**Issue by igormakunin** [gvlproject/gvl_image_playbook#41]
Tested on Image: GVL 4.1.0 Alpha (ami-0000396b)

Get Data > UCSC Main table browser returns an error because Galaxy is searching for the defunct GVL UCSC genome browser mirror. 

File to edit:
/mnt/galaxy/galaxy-app/tools/data_source/ucsc_tablebrowser.xml
Replace:
ucsc.genome.edu.au
with:
genome.ucsc.edu

**Comment by nuwang** [comment]
Fixed in commit: https://github.com/gvlproject/gvl.ansible.filesystem/commit/d05d04bddfc7a3015866d157fe0073e292c545a0
