### ISSUE TITLE
GVL-4.1 no visualisation for hg38 and some other assemblies on UCSC genome browser

### ISSUE THREAD

**Issue by igormakunin** [gvlproject/gvl_image_playbook#42]
Data for some genome assemblies, including the latest human genome hg38, are not displayed on UCSC genome browser. It would be useful to have links to UCSC for assemblies with build-in genome indices provided by GVL. 

Fix:
/mnt/galaxy/galaxy-app/tool-data/shared/ucsc/ucsc_build_sites.txt
Add sacCer2,sacCer3,hg38,bosTau7,rn6,rn5,oviAri3,ce10,danRer7 to 'main' line. I have impression the position is irrelevant. 
### 

Also, it is impossible to assign sacCer3 and ce10 to uploaded files, but GVL provides indices for these assemblies. To fix the issue add:
ce10    C. elegans Oct 2010 (WS220/ce10) (ce10) 
sacCer3 S. cerevisiae Apr 2011 (SacCer_Apr2011/saCer3) (sacCer3) 
to:
/mnt/galaxy/galaxy-app/tool-data/shared/ucsc/builds.txt 
NOTE: it has to be TAB-separated

**Comment by nuwang** [comment]
Fixed in commit: https://github.com/gvlproject/gvl.ansible.filesystem/commit/1413a8a9a7d5bc012db4311f2ffe049f308f5b76

**Comment by nuwang** [comment]
@igormakunin Will move to in-test and assign to you once latest build is complete.
