### ISSUE TITLE
mGVL (microgvl.ansible.filesystem) - ipython config does not exist .

### ISSUE THREAD

**Issue by mthang** [gvlproject/gvl_image_playbook#47]
The following error message occurred when I followed the steps on https://github.com/gvlproject/microgvl.ansible.filesystem to build the mGVL. There was no "ipython" folder found in this directory "/mnt/galaxy/galaxy-app/config/plugins/interactive_environments". 

fatal: [203.101.226.39]: FAILED! => {"changed": false, "checksum": "bb45406d527cc8e8f092c989ed3980a109d381c6", "failed": true, "invocation": {"module_args": {"backup": false, "content": null, "delimiter": null, "dest": "/mnt/galaxy/galaxy-app/config/plugins/interactive_environments/ipython/config/ipython.ini", "directory_mode": null, "follow": false, "force": true, "group": null, "mode": null, "original_basename": "ipython.ini", "owner": "galaxy", "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/tmp/ansible-tmp-1468216814.32-148946771149344/source", "validate": null}}, "msg": "Destination directory /mnt/galaxy/galaxy-app/config/plugins/interactive_environments/ipython/config does not exist"}

**Comment by nuwang** [comment]
Hi, this issue has been fixed in this commit: https://github.com/galaxyproject/ansible-cloudman-galaxy-setup/commit/714646dbc2729ffbec52a0a04cfa6e2d09fe1189 but the reason you're not getting that fix is because the Ansible Galaxy version has not been updated yet. As a workaround, can you try manually removing roles/galaxyprojectdotorg.cloudman-galaxy-setup, followed by a

```
git clone https://github.com/galaxyproject/ansible-cloudman-galaxy-setup galaxyprojectdotorg.cloudman-galaxy-setup
```

You may in fact, need to do this for a few other roles too. In the meantime, we'll try to organise a new release to ansible-galaxy. ping @afgane

**Comment by nuwang** [comment]
@afgane Should we consider skipping Ansible-Galaxy altogether and implementing this as tagged github releases + requirements.yml?

**Comment by Slugger70** [comment]
I always use the git HEAD for my builds and forgo the ansible-galaxy as they are usually out of sync.

**Comment by afgane** [comment]
I agree - removing dependency on Ansible-Galaxy is desirable. It should be done across all the roles too but one at a time is a good start.

**Comment by mthang** [comment]
Hi,this is the error message after I used the updated "galaxyprojectdotorg.cloudman-galaxy-setup" 
fatal: [203.101.228.142]: FAILED! => {"failed": true, "msg": "'ansbile_env' is undefined"}.

I found the code in this yml file
https://github.com/gvlproject/microgvl.ansible.filesystem/blob/master/tasks/install_linuxbrew.yml
- debug: msg="Current ansible envorinment = {{ ansbile_env }}"

**Comment by Slugger70** [comment]
What version of ansible are you using? ansible_env is a built in variable.

**Comment by mthang** [comment]
ansible 1.9.3 is the version in the GVL 4.0, but I need to upgrade the ansible by "pip install --upgrade ansible" .  The ansible version is 2.1.0 after the upgrade. 

Without upgrading the ansible, I encounter "deprecated feature" error.
ERROR: [DEPRECATED]: include + with_items is a removed deprecated feature (in /home/ubuntu/gvl.ansible.playbook/roles/galaxyprojectdotorg.galaxy-tools/tasks/tools.yml).  Please update your playbooks.

**Comment by nuwang** [comment]
@Slugger70 Just noticed that there is a typo in ansbile_env.

**Comment by madisonkeene** [comment]
this should be in the mGVL repo.
