### ISSUE TITLE
Workflow Edit problem

### ISSUE THREAD

**Issue by igormakunin** [gvlproject/gvl_image_playbook#54]
Workflow Edit does not work on GVL-4.1.0 (http://203.101.230.105/galaxy) or GVL4.0.0 updated to GVL-4.1.0 vai github (Galaxy-qld). I cannot open any existing workflow with edit: 'Loading workflow editor' goes forever.

**Comment by Slugger70** [comment]
Works fine on all of my 4.1s.. And on my 4.0s. I get same issue on your machine. Galaxy-mel is fine too.

**Comment by igormakunin** [comment]
Thank you, Simon! The issue exist on Galaxy-qld and two GVL-4.1 instances deployed in July. Also on Galaxy used for GenomeSpace testing: http://203.101.231.196/galaxy/

**Comment by igormakunin** [comment]
I just deployed a new GVL-4.1 - no problem with Workflow Edit. On another GVL-4.1 deployed from the same image (http://203.101.230.105/galaxy) Workflow Editor does not work.

**Comment by igormakunin** [comment]
I guess I should close the ticket because it is a local problem, eg Galaxy-qld, and the current GVL-4.1.0 instance does not have it.
