### ISSUE TITLE
SSH client and server X11UseLocalhost issue

### ISSUE THREAD

**Issue by dnbenso** [gvlproject/gvl_image_playbook#55]
/etc/ssh/ssh_config has an entry that belongs in /etc/ssh/sshd_config:  X11UseLocalhost

When the ssh client is used from the GVL instance it fails because the config file is invalid.
X11 forwarding doesn't work as entry is not in the ssh server configuration file.

**Comment by nuwang** [comment]
Fixed in commit: https://github.com/gvlproject/gvl.ansible.image/commit/fbed7927aabd1432241e443951cd3fc384ecfa70

A new image has also been built with the fix.
