### ISSUE TITLE
GenomeSpace Exporter > Dropbox error

### ISSUE THREAD

**Issue by igormakunin** [gvlproject/gvl_image_playbook#56]
I cannot export any file to my dropbox account by GenomeSpace Exporter on Galaxy-qld and a recently deployed GVL-4.1 instance. The error message says:
NotImplementedError: Don't know how to handle upload type: Dropbox
The Importer works with dropbox without any problem. 
I have a free dropbox account. 
Anyone had this problem or it is just me?

**Comment by madisonkeene** [comment]
Looking at the code it looks like dropbox upload is indeed not implemented - so the exporter won't work with dropbox. Are there plans to add this @nuwang ?

**Comment by nuwang** [comment]
The exporter only supports Amazon and Openstack at the moment. Support for Google drive and drop box has not yet been implemented.this can done if you think there'll be a big demand.

**Comment by madisonkeene** [comment]
hahaha fastest answer to my question ever @nuwang :)

**Comment by igormakunin** [comment]
Dropbox is available in the Connect menu. People may try it. Would it be ok to remove it? Is there any option to notify users that only import is supported?

**Comment by nuwang** [comment]
Genomespace does support all 4. I don't think we can ( or should) selectively disable because it affects non galaxy users.  implementing the other two can be done based on demand. What do you think?

**Comment by madisonkeene** [comment]
+1 to what you said Nuwan. Plus, removing functionality from GS is not worth it given there's a new version coming when i'm back from leave anyway

**Comment by igormakunin** [comment]
It would be useful to have the full support for dropbox. It is a popular storage.

**Comment by nuwang** [comment]
Ok. I'll look into adding support for it. We may as well implement all 4 for the sake of completeness.

**Comment by igormakunin** [comment]
That would be great!

**Comment by nuwang** [comment]
@igormakunin @madiflannery So it turns out that this problem occurs only with our genomespace mirror, probably because it's a bit out-of-date. Turns out that the new GenomeSpace handles dropbox uploads via S3 ( u'uploadType': u'S3') - and it's only the old genomespace version that sends an uploadType of 'dropbox'.  Once GenomeSpace is upgraded, this problem should disappear.
