### ISSUE TITLE
Better organisation of files in cloudman-gvl-410 bucket

### ISSUE THREAD

**Issue by nuwang** [gvlproject/gvl_image_playbook#58]
Improved organisation of the cloudman-gvl-410 bucket would be good to future proof things.
- Suggest moving webapollo under the packages folder.
- And moving all logos under a packages/icons folder.
  (IRIDA_DARK_50h.png  and WebApolloLogo.png)

@Slugger70 What do you think?
We can't move the cloudman stuff, but hopefully, the next version of cloudman won't be using these files at all.

BTW, the package_registry.yml file should be under packages, but there's one in root which NeCTAR isn't allowing me to delete.

**Comment by madisonkeene** [comment]
This is a great idea @nuwang :) More than happy to do this but it's not going to happen for at least a fortnight if thats OK (583274987 things to do)

**Comment by nuwang** [comment]
No probs. If it's mainly a matter of adjusting the package registry and shell script, I can do it. It may break icons for existing users if any. What do you think?

**Comment by madisonkeene** [comment]
Does the dashboard pull the icon from that bucket each time or download it locally to the machine? If it's the latter everything should be fine, if it's the former is it worth changing it to the latter (if that's even possible?). In terms of web apollo afaik we've only installed it on test machines so doesnt matter if the icon breaks :)

**Comment by nuwang** [comment]
Icon is a direct url so not fetched locally, but the package registry is cached, so it will have the wrong url if we move the icon. Since its just test instances i guess it doesn't matter. If @Slugger70 also sees no problem, I'll do it shortly

**Comment by madisonkeene** [comment]
Oh OK. Yeah should be all good for web apollo not sure about IRIDA though

**Comment by nuwang** [comment]
Done
