### ISSUE TITLE
genomespace module not installed on current filesystem build

### ISSUE THREAD

**Issue by Slugger70** [gvlproject/gvl_image_playbook#67]
Genomespace module not loaded. `python-genomespaceclient` needs to be included in requirements file. Once done galaxy needs to be restarted to load the python module

**Comment by nuwang** [comment]
It's installed now, but running the tool results in: "/mnt/galaxy/galaxy-app/.venv/bin/python: can't open file 'genomespace_importer.py': [Errno 2] No such file or directory"

**Comment by jessicachung** [comment]
In `/mnt/galaxy/galaxy-app/tools/genomespace/genomespace_importer.xml`, line 6 needs to be changed to:
```
        $__root_dir__/.venv/bin/python $__root_dir__/tools/genomespace/genomespace_importer.py
```
Once changed, genomespace import and export both work on Galaxy for gvl 4.2
