### ISSUE TITLE
Galaxy version bump to v17.01

### ISSUE THREAD

**Issue by Slugger70** [gvlproject/gvl_image_playbook#68]
Bump Galaxy version to 17.01

**Comment by Slugger70** [comment]
Nuwan has merged 17.01 from galaxy project to our branch. Genomespace additions are almost complete.

**Comment by Slugger70** [comment]
Changes are required in the `galaxy.ini` file
* addition of `conda_auto_init = True`
Plus maybe others

`shed_tool_conf_cloud.xml` is no longer used by cloudman - needs to be `shed_tool_conf.xml` now. symlink? Or change to `galaxy.ini`

**Comment by nuwang** [comment]
shed_tool_conf_cloud renamed to shed_tool_conf.xml in  commit: https://github.com/gvlproject/gvl.ansible.filesystem/commit/16f7f407da3ed084a77d0a6a60d4dbe06821d294
