### ISSUE TITLE
Upgrade SLURM to latest

### ISSUE THREAD

**Issue by nuwang** [gvlproject/gvl_image_playbook#71]

**Comment by nuwang** [comment]
@dnbenso It should already be installing the latest slurm. Is that not the case?

**Comment by dnbenso** [comment]
Yeah, lets resolve this for now.  QFAB staff raised it as an issue and I wrongly thought that it wasn't the latest.  I believe they may have been talking about the fact that the version number of 2.6.5-1 does match the 15.08.7 build tag on the debian package? The latest version of slurm source is 17.02.  We however do NOT want to be running slurm from source code.  BAD idea as you have to keep up with patches etc.  Much better to stick with a curated version of the package.
