### ISSUE TITLE
Role not found: galaxyprojectdotorg.cloudman-database was NOT installed successfully

### ISSUE THREAD

**Issue by BrunoEVCosta** [gvlproject/gvl_image_playbook#75]
Hello I'm trying to follow your guide to create a gvl image, but I get this error when trying to install the roles. Is this an ansible problem or are there broken dependencies?

-> $ ansible-galaxy install -r requirements.yml -p roles     
- extracting gvl.ansible.filesystem.presetup to roles/gvl.ansible.filesystem.presetup
- gvl.ansible.filesystem.presetup was installed successfully
- extracting gvl.ansible.filesystem to roles/gvl.ansible.filesystem
- gvl.ansible.filesystem was installed successfully
 [WARNING]: - dependency gvl.ansible.filesystem.presetup from role gvl.ansible.filesystem differs from already installed version (), skipping

- adding dependency: galaxyprojectdotorg.cloudman-database
- adding dependency: galaxyprojectdotorg.galaxy
- adding dependency: galaxyprojectdotorg.trackster
- adding dependency: galaxyprojectdotorg.cloudman-galaxy-setup
- adding dependency: galaxyprojectdotorg.galaxy-tools
- extracting microgvl.ansible.filesystem to roles/microgvl.ansible.filesystem
- microgvl.ansible.filesystem was installed successfully
 [WARNING]: - dependency gvl.ansible.filesystem from role microgvl.ansible.filesystem differs from already installed version (), skipping

- extracting gvl.ansible.image to roles/gvl.ansible.image
- gvl.ansible.image was installed successfully
- adding dependency: galaxyprojectdotorg.cloudman-image
- downloading role 'cloudman-database', owned by galaxyprojectdotorg
 [WARNING]: - galaxyprojectdotorg.cloudman-database was NOT installed successfully: - sorry, galaxyprojectdotorg.cloudman-database was not found on
https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

System info:
Clean image of Ubuntu 14.04
With the default ansible version from the ubuntu repository all roles where not found.
ansible:
  Installed: 2.3.1.0-1ppa~trusty
  Candidate: 2.3.1.0-1ppa~trusty
  Version table:
 *** 2.3.1.0-1ppa~trusty 0
        500 http://ppa.launchpad.net/ansible/ansible/ubuntu/ trusty/main amd64 Packages

**Comment by nuwang** [comment]
Hi @netbofia, Thanks for reporting this. This was because the ansible-galaxy roles were recently renamed. I've just made a patch that should fix this: https://github.com/gvlproject/gvl.ansible.playbook/commit/c4973fd8cd9ffd64de66b4e23de26ea39f6669eb

Also wanted to alert you that the latest version of the GVL (4.2) has been updated to use Ubuntu 16.04. We had missed updating the documentation and have done so now.

Let us know if you run into any more issues - happy to help. If you don't plan to make any customisations, and just want to get the GVL running, we can also make a copy of the GVL image available for download so you can save some time.

**Comment by JoaoMFCardoso** [comment]
Where can we download the default GVL image? We set ourselves to follow the playbook because we couldn't find it on the GVL website.

Anyway, thanks for the quick reply!

**Comment by BrunoEVCosta** [comment]
Wow, many thanks for the quick reply. 

Me and @JoaoMFCardoso  will try to follow the updated guide and supply more feed back if any other problems arise. 

Yes a copy of the GVL image would actually be more useful. For the time being, we do not plan on making customizations.

**Comment by nuwang** [comment]
@JoaoMFCardoso @netbofia I've updated the playbook instructions to include some download links to the qcow2 image - I assume you're trying to get this running on an OpenStack cloud? The 4.2.0 image is the latest and greatest - we use it now but it's still in beta - we plan to finalise the release next month so any feedback you have would be very useful.

Once it's set up on your cloud, we can add the image to the launcher (https://beta.launch.usegalaxy.org). Just e-mail us or post here and we can get that going.

**Comment by JoaoMFCardoso** [comment]
@nuwang @netbofia yes. The idea is to set up VM's in our OpenStack service with your images.

I've pushed through with the guide, but I was suck analyzing the packer.json file. I might be completely off here, but I was trying to simplify it as to not include any AWS references and just link it with our own Openstack.

Is this something we can do?

**Comment by BrunoEVCosta** [comment]
Thanks, for all the help. This can now be marked as solved.

**Comment by nuwang** [comment]
@JoaoMFCardoso Yes. The easiest way to do this is to use the -only flag in packer.
packer build -only=openstack packer.json
