### ISSUE TITLE
Genomespace push doesn't work in 4.2

### ISSUE THREAD

**Issue by Slugger70** [gvlproject/gvl_image_playbook#85]
It looks as though Genomespace push doesn't wrok at all in 4.2. Genome space pull works just fine.

**Comment by Slugger70** [comment]
fixed in the new filesystem ansible. Will be in the new build.

**Comment by nuwang** [comment]
Added handling for compressed extensions: https://github.com/gvlproject/galaxy/commit/d37a2a9de2713d438a3a19dd1b21f8e2c7631bcb

**Comment by Slugger70** [comment]
Tested on Vanilla 4.2 and it all works
