### ISSUE TITLE
DEXseq, DEseq2, DEseq, edgeR errors on GVL-4.0.0

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/gvl_image_playbook#9]

**Comment by madisonkeene** [comment]
DEXseq, DEseq2, DEseq produce errors, edgeR has an empty output. These are tools from the RNA Analysis menu. I've tested DEXseq and DEseq2 on Galaxy-mel - the same problem, the tools produce errors.

Differential Count model works fine (it has DEseq2 and edgeR)

**Comment by igormakunin** [comment]
@nuwang DEXseq, DEseq and edgeR are all gone. DEseq2 works with the new (additional) htseq count tool. I guess the ticket can be closed.
